import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-50 text-slate-950">
        <nav aria-label="Main navigation" className="flex flex-wrap gap-5 border-b border-slate-200 bg-white px-6 py-3 text-sm font-medium">
          {[["Dashboard", "/"], ["Properties", "/properties"], ["Contacts", "/contacts"], ["Pipeline", "/pipeline"], ["Tasks", "/tasks"], ["Follow-Ups", "/follow-ups"]].map(([label, href]) => <Link key={href} href={href} className="hover:underline">{label}</Link>)}
        </nav>{children}</body>
    </html>
  );
}
